/**
 * Slack mrkdwn and Block Kit Formatting Utilities.
 * 
 * Translates standard markdown generated by Gemini into Slack-specific mrkdwn
 * syntax and rich Block Kit message cards.
 */

/**
 * Converts standard Markdown syntax into Slack mrkdwn syntax.
 * - Bold: **text** -> *text*
 * - Links: [text](url) -> <url|text>
 * - Headings: ### Header -> *Header*
 */
export function formatMarkdownForSlack(text: string): string {
  if (!text) return '';

  let formatted = text;

  // Replace markdown headers (# Header, ## Header, ### Header) with bold text
  formatted = formatted.replace(/^#{1,6}\s+(.+)$/gm, '*$1*');

  // Convert standard markdown bold **bold** or __bold__ to Slack *bold*
  // Avoid replacing bold inside existing code blocks
  formatted = formatted.replace(/\*\*(.+?)\*\*/g, '*$1*');
  formatted = formatted.replace(/__(.+?)__/g, '*$1*');

  // Convert markdown links [title](url) to Slack <url|title>
  formatted = formatted.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<$2|$1>');

  return formatted.trim();
}

/**
 * Wraps formatted text into Slack Block Kit payload with optional header and metadata footer.
 */
export function createSlackBlocks(content: string, title?: string): any[] {
  const blocks: any[] = [];

  if (title) {
    blocks.push({
      type: 'header',
      text: {
        type: 'plain_text',
        text: title,
        emoji: true,
      },
    });
  }

  // Slack section blocks have a 3000 character limit. If content exceeds, split into multiple sections.
  const formattedText = formatMarkdownForSlack(content);
  const maxSectionLength = 2900;

  if (formattedText.length <= maxSectionLength) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: formattedText,
      },
    });
  } else {
    let remaining = formattedText;
    while (remaining.length > 0) {
      let chunk = remaining.slice(0, maxSectionLength);
      // Try to split on newline
      const lastNewline = chunk.lastIndexOf('\n');
      if (lastNewline > maxSectionLength * 0.7) {
        chunk = remaining.slice(0, lastNewline);
        remaining = remaining.slice(lastNewline + 1);
      } else {
        remaining = remaining.slice(maxSectionLength);
      }
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: chunk,
        },
      });
    }
  }

  // Add subtle divider and footer badge
  blocks.push({ type: 'divider' });
  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: '⚡ *Google AI Studio* • Powered by Gemini 3.6 Flash',
      },
    ],
  });

  return blocks;
}
